### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by tatsuhiko-nakayama** [tatsuhiko-nakayama/furima-29715#9]
# URL
https://furima-29715.herokuapp.com/

# Basic認証
ID : admin
PASS : 2222

# 出品者
Email : furima@1
Pass : furima1

# 購入者
Email : furima@2
Pass : furima2 

# カード情報
number : 4242424242424242
month : 1
year : 23
cvc : 123

**Comment by mutorisa** [comment]
中山さん、ご提出ありがとうございます！
挙動確認させて頂きましたが、全く問題ございませんでしたのでLGTMとさせて頂きます🎉
おめでとうございます✨


**※確認したのは必須機能のみで追加実装した機能については確認していません。
そのため追加機能を実装している場合は、正しく想定通りの挙動であるかご自身で再度確認をお願いいたします。**
